name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip extension
        run: zip -r citepoint.zip . -x "*.git*" "node_modules/*"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: citepoint-extension
          path: citepoint.zip
